/**
 * Bring any ComfyUI workflow into the pipeline:
 *   1. uiToApi()      — convert the UI/graph format (what the editor saves and what Comfy Cloud share links return)
 *                        into the API format that /prompt accepts. Uses `widgets_values_named` when the frontend
 *                        saved it, otherwise maps `widgets_values` positionally with /object_info.
 *   2. suggestMapping() — guess which node inputs the app should fill (images, source video, prompt, seed…).
 *   3. applyMapping()   — at run time, write the pipeline's values into those inputs.
 */

const SKIP_TYPES = new Set(['Note', 'MarkdownNote', 'PrimitiveNode', 'Reroute', 'GroupNode', 'Label (rgthree)', 'Fast Groups Bypasser (rgthree)']);
const WIDGET_TYPES = new Set(['INT', 'FLOAT', 'STRING', 'BOOLEAN', 'COMBO']);

/** Variables the pipeline can inject, per stage. */
export const VARIABLES = {
  image: {
    PROMPT: 'Nano Banana prompt (generated by the app)',
    SEED: 'Random seed',
    IMAGE_1: 'Model photo #1 (front face)', IMAGE_2: 'Model photo #2', IMAGE_3: 'Model photo #3',
    IMAGE_4: 'Model photo #4', IMAGE_5: 'Model photo #5 (body)', IMAGE_6: 'Model photo #6',
    SOURCE_FRAME: 'Original reel frame',
    ASPECT_RATIO: 'Aspect ratio (9:16)', RESOLUTION: 'Resolution',
  },
  video: {
    PROMPT: 'Video prompt (generated by the app)',
    SEED: 'Random seed',
    FIRST_FRAME: 'Approved first frame',
    MODEL_IMAGE: 'Model face photo',
    SOURCE_VIDEO: 'Original reel video',
    DURATION: 'Duration', RESOLUTION: 'Resolution', RATIO: 'Aspect ratio',
  },
};

export function isUiWorkflow(wf) {
  return wf && Array.isArray(wf.nodes) && (Array.isArray(wf.links) || wf.links === undefined);
}

/**
 * @param ui        UI-format workflow { nodes, links, definitions? }
 * @param objectInfo map class_type -> object_info entry (may be partial)
 */
export function uiToApi(ui, objectInfo = {}) {
  const warnings = [];
  if (ui.definitions?.subgraphs?.length) warnings.push('The workflow uses subgraphs — if it fails, open it in ComfyUI, run "Unpack subgraph" and export it in API format.');
  const nodes = new Map((ui.nodes || []).map((n) => [n.id, n]));
  // links: [id, origin_id, origin_slot, target_id, target_slot, type] (array) or objects in newer versions
  const links = new Map();
  for (const l of ui.links || []) {
    if (Array.isArray(l)) links.set(l[0], { origin: l[1], slot: l[2] });
    else if (l && typeof l === 'object') links.set(l.id, { origin: l.origin_id, slot: l.origin_slot });
  }

  // Follow Reroute nodes back to the real source; resolve PrimitiveNodes to their value.
  const resolve = (linkId, depth = 0) => {
    const l = links.get(linkId);
    if (!l || depth > 20) return null;
    const src = nodes.get(l.origin);
    if (!src) return null;
    if (src.type === 'Reroute') {
      const inLink = src.inputs?.[0]?.link;
      return inLink != null ? resolve(inLink, depth + 1) : null;
    }
    if (src.type === 'PrimitiveNode') return { value: src.widgets_values?.[0] };
    if (src.mode === 4) { // bypassed: pass through the first input of the same type
      const out = src.outputs?.[l.slot];
      const inp = (src.inputs || []).find((i) => i.type === out?.type && i.link != null);
      return inp ? resolve(inp.link, depth + 1) : null;
    }
    return { link: [String(src.id), l.slot] };
  };

  const api = {};
  for (const n of nodes.values()) {
    if (SKIP_TYPES.has(n.type) || n.mode === 2 || n.mode === 4) continue; // notes, muted, bypassed
    const inputs = {};
    const info = objectInfo[n.type];

    // 1) widget values
    if (n.widgets_values_named && typeof n.widgets_values_named === 'object') {
      for (const [k, v] of Object.entries(n.widgets_values_named)) if (k !== 'control_after_generate') inputs[k] = v;
    } else if (n.widgets_values && !Array.isArray(n.widgets_values) && typeof n.widgets_values === 'object') {
      Object.assign(inputs, n.widgets_values); // some custom nodes store a dict
    } else if (Array.isArray(n.widgets_values) && n.widgets_values.length) {
      if (!info) {
        warnings.push(`Node ${n.type} #${n.id}: no definition (/object_info) to map the widgets.`);
      } else {
        const vals = [...n.widgets_values];
        let i = 0;
        // Walk the inputs in declaration order, consuming widget values; dynamic combos (v3 nodes such as
        // Wan 3.0 / Nano Banana / SaveVideo) expand into "<name>.<child>" inputs of the selected option.
        const walk = (inputDict, orderDict, prefix) => {
          const order = [...(orderDict?.required || Object.keys(inputDict?.required || {})), ...(orderDict?.optional || Object.keys(inputDict?.optional || {}))];
          const spec = { ...(inputDict?.required || {}), ...(inputDict?.optional || {}) };
          for (const name of order) {
            const def = spec[name];
            if (!def || i >= vals.length) continue;
            const [type, opts = {}] = def;
            const key = prefix + name;
            if (type === 'COMFY_DYNAMICCOMBO_V3') {
              const v = vals[i++];
              inputs[key] = v;
              const opt = (opts.options || []).find((o) => o.key === v);
              if (opt) walk(opt.inputs, null, `${key}.`);
              continue;
            }
            const isWidget = Array.isArray(type) || WIDGET_TYPES.has(type);
            if (!isWidget) continue;
            inputs[key] = vals[i++];
            if (opts.control_after_generate || ((name === 'seed' || name === 'noise_seed') && typeof vals[i] === 'string' && /^(fixed|increment|decrement|randomize)$/.test(vals[i]))) i++;
            if ((opts.image_upload || opts.video_upload) && (vals[i] === 'image' || vals[i] === 'video')) i++;
          }
        };
        walk(info.input, info.input_order, '');
      }
    }

    // 2) links (override widgets converted to inputs)
    for (const inp of n.inputs || []) {
      if (inp.link == null) continue;
      const r = resolve(inp.link);
      if (!r) continue;
      inputs[inp.name] = r.link || r.value;
    }
    api[String(n.id)] = { class_type: n.type, inputs, _meta: { title: n.title || n.type } };
  }
  if (!Object.keys(api).length) warnings.push('No executable node found.');
  return { api, warnings };
}

/** Guess mapping { "<nodeId>.<input>": VAR } for a stage. */
export function suggestMapping(api, kind) {
  const map = {};
  const entries = Object.entries(api);
  const title = (n) => (n._meta?.title || '').toLowerCase();

  // Images
  const loaders = entries.filter(([, n]) => n.class_type === 'LoadImage' || /LoadImage/i.test(n.class_type));
  const videos = entries.filter(([, n]) => /LoadVideo|VHS_LoadVideo/i.test(n.class_type));
  if (kind === 'image') {
    const frame = loaders.find(([, n]) => /frame|source|reel|original|cena|scene/.test(title(n)));
    let k = 1;
    for (const [id, n] of loaders) {
      const key = 'image' in n.inputs ? 'image' : Object.keys(n.inputs)[0];
      if (frame && id === frame[0]) map[`${id}.${key}`] = 'SOURCE_FRAME';
      else if (k <= 6) map[`${id}.${key}`] = `IMAGE_${k++}`;
    }
    if (!frame && loaders.length >= 2) map[`${loaders.at(-1)[0]}.${'image' in loaders.at(-1)[1].inputs ? 'image' : Object.keys(loaders.at(-1)[1].inputs)[0]}`] = 'SOURCE_FRAME';
  } else {
    const face = loaders.find(([, n]) => /face|rosto|character|model|ref/.test(title(n)));
    for (const [id, n] of loaders) {
      const key = 'image' in n.inputs ? 'image' : Object.keys(n.inputs)[0];
      map[`${id}.${key}`] = face && id === face[0] && loaders.length > 1 ? 'MODEL_IMAGE' : 'FIRST_FRAME';
    }
    for (const [id, n] of videos) map[`${id}.${'file' in n.inputs ? 'file' : 'video' in n.inputs ? 'video' : Object.keys(n.inputs)[0]}`] = 'SOURCE_VIDEO';
  }

  // Prompt: known partner nodes first, then positive CLIPTextEncode
  for (const [id, n] of entries) {
    for (const key of ['model.prompt', 'prompt', 'positive_prompt', 'text_prompt']) {
      if (typeof n.inputs[key] === 'string') { map[`${id}.${key}`] = 'PROMPT'; break; }
    }
  }
  if (!Object.values(map).includes('PROMPT')) {
    // CLIPTextEncode feeding a "positive" input
    const pos = new Set();
    for (const [, n] of entries) if (Array.isArray(n.inputs.positive)) pos.add(n.inputs.positive[0]);
    for (const [id, n] of entries) if (n.class_type === 'CLIPTextEncode' && (pos.has(id) || !/neg/.test(title(n))) && typeof n.inputs.text === 'string') { map[`${id}.text`] = 'PROMPT'; break; }
  }
  // Seeds
  for (const [id, n] of entries) for (const key of ['seed', 'noise_seed']) if (typeof n.inputs[key] === 'number') map[`${id}.${key}`] = 'SEED';
  // Video params on Wan partner nodes
  if (kind === 'video') for (const [id, n] of entries) if ('model.duration' in n.inputs) map[`${id}.model.duration`] = 'DURATION';
  return map;
}

/** Write variables into the mapped inputs. Mapping keys are "<nodeId>.<input name>" (input names may contain dots). */
export function applyMapping(api, mapping = {}, vars = {}) {
  const wf = structuredClone(api);
  for (const [key, variable] of Object.entries(mapping)) {
    if (!variable || !(variable in vars)) continue;
    const dot = key.indexOf('.');
    const id = key.slice(0, dot);
    const input = key.slice(dot + 1);
    if (!wf[id]) continue;
    const v = vars[variable];
    if (v === '' || v === null || v === undefined) {
      // Optional input not available (e.g. no source video): drop it so ComfyUI doesn't choke.
      if (typeof wf[id].inputs[input] === 'string') continue;
    }
    wf[id].inputs[input] = v;
  }
  return wf;
}

/** Everything a user might want to map, for the mapping UI. */
export function mappableInputs(api) {
  const out = [];
  for (const [id, n] of Object.entries(api)) {
    for (const [k, v] of Object.entries(n.inputs || {})) {
      if (Array.isArray(v)) continue; // links
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        out.push({ key: `${id}.${k}`, node: id, type: n.class_type, title: n._meta?.title || n.class_type, input: k, value: typeof v === 'string' && v.length > 80 ? v.slice(0, 80) + '…' : v });
      }
    }
  }
  return out;
}
